# GENERAL
playing: Beta (06.01.2022)

# XP REWARDS
word-reward-xp: .2
bumper-reward-xp: 15
helper-reward-xp: 30

# EMOJIS
bar-fill: ":blue_square:"
bar-empty: ":white_large_square:"

# CHANNELS
invite-channels: [657287172474273822, 921468392618209318]
rank-message-channels: [657287172474273822, 921468392618209318] # Rank reward message channel